trigger:
  branches:
    include:
      - master

pr:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-22.04'

variables:
  - name: workingDirectory
    value: 'terraform'


stages:
  - stage: Dev
    displayName: "Deploy to Dev"
    condition: eq(variables['Build.Reason'], 'PullRequest')
    jobs:
      - job: TerraformDev
        displayName: "Terraform Apply to Dev"
        steps:
          - checkout: self

          - task: DownloadSecureFile@1
            name: downloadTfvars
            inputs:
              secureFile: 'dev.tfvars'

          - task: TerraformTaskV4@4
            displayName: 'Terraform Init'
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'BeStrong-AI'
              backendAzureRmResourceGroupName: 'BeStrong-AI'
              backendAzureRmStorageAccountName: 'tfstatebestrong3246'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'dev.tfstate'
              workingDirectory: '$(workingDirectory)'

          - task: TerraformTaskV4@4
            displayName: 'Terraform Validate'
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '$(workingDirectory)'

          - task: TerraformTaskV4@4
            displayName: 'Terraform Plan'
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(workingDirectory)'
              environmentServiceNameAzureRM: 'BeStrong-AI'
              commandOptions: '-var-file=$(downloadTfvars.secureFilePath)'

          - task: TerraformTaskV4@4
            displayName: 'Terraform Apply'
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '$(workingDirectory)'
              environmentServiceNameAzureRM: 'BeStrong-AI'
              commandOptions: '-var-file=$(downloadTfvars.secureFilePath) -auto-approve'

  - stage: Approval
    displayName: "Manual Approval to Prod"
    dependsOn: Dev
    condition: eq(variables['Build.Reason'], 'PullRequest')
    jobs:
      - job: WaitForApproval
        steps:
          - task: ManualValidation@0
            inputs:
              instructions: "Approve to deploy to PROD"
              onTimeout: 'reject'
              timeout: '1d'

  - stage: Prod
    displayName: "Deploy to Prod"
    dependsOn: Approval
    condition: eq(variables['Build.Reason'], 'IndividualCI')
    jobs:
      - job: TerraformProd
        displayName: "Terraform Apply to Prod"
        steps:
          - checkout: self

          - task: DownloadSecureFile@1
            name: downloadTfvars
            inputs:
              secureFile: 'prod.tfvars'

          - task: TerraformTaskV4@4
            displayName: 'Terraform Init'
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'BeStrong-AI'
              backendAzureRmResourceGroupName: 'BeStrong-AI'
              backendAzureRmStorageAccountName: 'tfstatebestrong324'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'prod.tfstate'
              workingDirectory: '$(workingDirectory)'

          - task: TerraformTaskV4@4
            displayName: 'Terraform Validate'
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '$(workingDirectory)'

          - task: TerraformTaskV4@4
            displayName: 'Terraform Plan'
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(workingDirectory)'
              environmentServiceNameAzureRM: 'BeStrong-AI'
              commandOptions: '-var-file=$(downloadTfvars.secureFilePath)'

          - task: TerraformTaskV4@4
            displayName: 'Terraform Apply'
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '$(workingDirectory)'
              environmentServiceNameAzureRM: 'BeStrong-AI'
              commandOptions: '-var-file=$(downloadTfvars.secureFilePath) -auto-approve'